export const DATA_SOURCE_STATUS = Object.freeze({
  READY: 'ready',
  PENDING: 'pending',
  NOT_STARTED: 'not_started',
  AVAILABLE_NO_LOCAL_FEATURES: 'available_no_local_features',
  UNAVAILABLE: 'unavailable',
  INVALID: 'invalid',
})

function defineSource(source) {
  return Object.freeze(source)
}

export const dataSources = Object.freeze([
  defineSource({
    id: 'osm-walking-network',
    name: 'OpenStreetMap Walking Network',
    provider: 'OpenStreetMap contributors',
    sourcePage: 'https://www.openstreetmap.org/',
    purpose: '通过 OSMnx 建立步行道路网',
    status: DATA_SOURCE_STATUS.READY,
    localRawPath: 'data/raw/osm/',
    processedPath: 'data/processed/osm/',
    browserPath: 'public/data/graph.json',
    required: true,
    priority: 'P0',
    format: 'OSM/Overpass response; processed browser format: JSON',
    license: 'ODbL',
    notes: 'M2 真实 walk network 已由 M4 enrichment；Browser Graph Schema 1.1.0，不改变道路拓扑。',
    showInStatus: true,
  }),
  defineSource({
    id: 'tokyo-green-gis',
    name: '緑のオープンデータ（GISデータ）',
    provider: '东京都都市整备局 都市づくり政策部緑地景観課',
    sourcePage: 'https://catalog.data.metro.tokyo.lg.jp/dataset/t000008d2000000024',
    purpose: '以语义白名单实际绿色覆盖 Polygon 计算 green_score',
    status: DATA_SOURCE_STATUS.READY,
    localRawPath: 'data/raw/green/',
    processedPath: 'data/processed/green/',
    browserPath: 'public/data/environment_metadata.json',
    required: true,
    priority: 'P0',
    format: 'ESRI Shapefile ZIP；processed GPKG；edge fields in JSON',
    license: 'CC BY（所用资源）',
    notes: 'M4 已通过 Raw → Schema Inspection → Enrichment 门禁；仅纳入官方定义明确的实际绿色覆盖 Polygon。',
    showInStatus: true,
  }),
  defineSource({
    id: 'tokyowater-drinking-stations',
    name: 'Tokyowater Drinking Station',
    provider: '东京都水道局',
    sourcePage: 'https://catalog.data.metro.tokyo.lg.jp/dataset/t000019d0000000003',
    purpose: '为后续最近饮水点、water_penalty 和路线饮水点信息提供输入',
    status: DATA_SOURCE_STATUS.READY,
    localRawPath: 'data/raw/drinking_station/',
    processedPath: 'data/processed/drinking_station/',
    browserPath: 'public/data/drinking_stations.geojson',
    required: false,
    priority: 'P1',
    format: 'CSV',
    license: 'CC BY',
    notes: 'M4 使用 801 个有效官方 Point 计算 Edge 最近距离；Demo GeoJSON 发布其中 5 个本地点。',
    showInStatus: true,
  }),
  defineSource({
    id: 'tokyo-street-trees',
    name: 'Tokyo Street Trees',
    provider: '东京都建设局',
    sourcePage: 'https://catalog.data.metro.tokyo.lg.jp/dataset/t000014d2000000029',
    purpose: '未来 tree_score 候选输入',
    status: DATA_SOURCE_STATUS.NOT_STARTED,
    localRawPath: 'data/raw/trees/',
    processedPath: 'data/processed/environment/',
    browserPath: null,
    required: false,
    priority: 'P2',
    format: 'CSV',
    license: 'CC BY',
    notes: 'M1 只登记。使用前必须验证字段是否能表达空间位置并覆盖 Demo 区域。',
    showInStatus: false,
  }),
  defineSource({
    id: 'plateau-3d-buildings',
    name: 'Project PLATEAU 3D Buildings',
    provider: '国土交通省',
    sourcePage: 'https://www.mlit.go.jp/plateau/',
    purpose: '未来 building footprint、building height 和 shade_score 候选输入',
    status: DATA_SOURCE_STATUS.NOT_STARTED,
    localRawPath: 'data/raw/plateau/',
    processedPath: 'data/processed/environment/',
    browserPath: null,
    required: false,
    priority: 'P2',
    format: null,
    license: null,
    notes: 'M1 只登记官方入口，禁止下载整个东京 PLATEAU 数据。具体资源的格式和许可证尚未核验。',
    showInStatus: false,
  }),
  defineSource({
    id: 'jma-weather',
    name: 'JMA Weather Data',
    provider: '日本气象厅',
    sourcePage: 'https://www.jma.go.jp/jma/index.html',
    purpose: '未来 Environment Multiplier 候选输入',
    status: DATA_SOURCE_STATUS.NOT_STARTED,
    localRawPath: 'data/raw/weather/',
    processedPath: 'data/processed/environment/',
    browserPath: null,
    required: false,
    priority: 'P2',
    format: null,
    license: null,
    notes: '不得将天气数据描述为某条道路的真实气温。具体资源、格式和使用条款尚未核验。',
    showInStatus: false,
  }),
])

export const statusDataSources = Object.freeze(
  dataSources.filter((source) => source.showInStatus),
)
